### ISSUE TITLE
Installation process

### ISSUE THREAD

**Issue by mathisjay** [DNNCommunity/Dnn.WebAnalytics#1]
This module requires several large data files to be located in the App_Data folder and also a .config file to be located in the web root.   The data files are much too large for the module installer process.  And, anyways I am not sure how to work them into the module manifest.

Here are files that need to be located in the App_Data folder:
51Degrees.dat - provides device information for requests made to the website
GeoIP2-City.mmdb - provides geocoding service for IP addresses

This file needs to be the web root:
51Degrees.mobi.config

**Comment by david-poindexter** [comment]
@mathisjay are you saying the files are too big to...

1. Upload as a part of the install extension user experience?
2. Be handled by the DNN extension installer (even if installed via /Install folder on server)?
3. Something else?

**Comment by mathisjay** [comment]
well, for starters, the 51degrees.dat file is over 100MB and the GitHub limit is 100MB...

But, there is a file size limit on the module installer also.

I didnt try putting it directly in the /install folder, that might work.

Also, I wasnt sure about how to get the manifest to put the file in the AppData folder.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hismightiness** [comment]
The 51Degrees file probably shouldn't be part of the install or check-in at all.  Instead, it should be integrated with their API and then the API would download it after install.

**Comment by mathisjay** [comment]
I don’t understand that…   The code just expects the .dat file to be there.  If there is some magic sauce to make that happen automatically, then I am all for it.

**Comment by david-poindexter** [comment]
@mathisjay are you using [THIS](https://github.com/51Degrees/dotNET-Device-Detection) via NuGet or something else?

**Comment by david-poindexter** [comment]
Here is the .NET API - https://51degrees.com/Developers/Documentation/APIs/NET-V32

**Comment by david-poindexter** [comment]
Here is the Cloud API - https://51degrees.com/support/documentation/cloud-api

**Comment by hismightiness** [comment]
Also, I know and work with the folks at 51Degrees, so I can get them to help.  :)

**Comment by hismightiness** [comment]
Thanks for providing those links, @david-poindexter.

@mathisjay The file was only (manually) put there originally as a short-cut - so-to-speak.  At the time, there was no need or desire to properly implement the API that 51Degrees has, because the file was already there and we never thought the code would become public in any way.  (So, it wasn't productized for other use cases/websites.)  

If we do properly implement it to use their API, it will lower the footprint, prevent the need for committing the data, and also regularly receive updated mobile information.

**Comment by mathisjay** [comment]
thats awesome.  im all for it

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by skamphuis** [comment]
I guess I'm a bit late to the party, but I added an msbuild-packaging script today. I ran into a missing file though: the .mmdb file. Been trying to find it here https://github.com/maxmind but maybe anyone has a link to it?

**Comment by mathisjay** [comment]
I was in the package I was handed from Shaun

I think it come from here:
https://dev.maxmind.com/geoip/geoip2/geolite2/

**Comment by skamphuis** [comment]
> 
> 
> Thanks for providing those links, @david-poindexter.
> 
> @mathisjay The file was only (manually) put there originally as a short-cut - so-to-speak. At the time, there was no need or desire to properly implement the API that 51Degrees has, because the file was already there and we never thought the code would become public in any way. (So, it wasn't productized for other use cases/websites.)
> 
> If we do properly implement it to use their API, it will lower the footprint, prevent the need for committing the data, and also regularly receive updated mobile information.

It would be nice however, to be able to use the downloaded file as an option. I know of at least one client where the server is not able to access external API's for security reasons.
