### ISSUE TITLE
Module is not Azure Friendly

### ISSUE THREAD

**Issue by hismightiness** [DNNCommunity/Dnn.WebAnalytics#2]
If we were to install this module in Azure, it would not work.  The SQL and CS files need to be updated to support Azure, should we ever move the website there.  (or anyone use this there...)

The SQL statements were missing DNN tokens as well.

In order to perform these updates and ensure they build properly, the following needs to be done as well:

- Update project to use any IIS configuration (website path/URL)
- Update references to not assume the website folder is there and that the dependent DLL's will be present.

**Comment by david-poindexter** [comment]
Manually closing per #3
